ALTER PROCEDURE "DBA"."INSERT_HIGHEST_RANKED_PICKS"(
@source_name VARCHAR(40),
@source_list VARCHAR(40),
@strat_column VARCHAR(40),
@filter_name LONG VARCHAR,
@aoi_name VARCHAR(40))
BEGIN
DECLARE @sql_statement LONG VARCHAR;
SET @sql_statement = 'CREATE TABLE #TEMPFILTER ("UWI" VARCHAR(26) NOT NULL, PRIMARY KEY ("UWI" ASC))';
EXECUTE IMMEDIATE @sql_statement;
if LENGTH(@filter_name) = 0 THEN
SET @sql_statement = 'INSERT INTO #TEMPFILTER (SELECT UWI FROM WELL)';
ELSE
SET @sql_statement = 'LOAD TABLE #TEMPFILTER FROM ''' || @filter_name || '''';
END IF;
EXECUTE IMMEDIATE @sql_statement;
IF LENGTH(@aoi_name) > 0 THEN
SET @sql_statement = 'CREATE TABLE #TEMPAOIVIEW ("UWI" VARCHAR(26) NOT NULL, PRIMARY KEY ("UWI" ASC))';
EXECUTE IMMEDIATE @sql_statement;
SET @aoi_name = 'WellHeader_' || @aoi_name;
SET @sql_statement = 'INSERT INTO #TEMPAOIVIEW (SELECT "Well ID" FROM ' || @aoi_name || ')';
EXECUTE IMMEDIATE @sql_statement;
END IF;
CREATE TABLE #TEMPCOLUMN ("FORM_ID" VARCHAR(20) NOT NULL, PRIMARY KEY ("FORM_ID" ASC));
SET @sql_statement = 'INSERT INTO #TEMPCOLUMN (FORM_ID) (SELECT FORM_ID FROM "DBA"."FORMATION" WHERE COLUMN_NAME = ''' || @strat_column || ''')';
EXECUTE IMMEDIATE @sql_statement;
SET @sql_statement = 'INSERT INTO #TEMPCOLUMN (FORM_ID) ON EXISTING UPDATE
(SELECT b.MEMBER_FM_ID FROM FM_ALIAS_GROUP_MEMBER as b WHERE b.FORM_ID IN (SELECT FORM_ID FROM "DBA"."FORMATION" WHERE COLUMN_NAME = ''' || @strat_column || ''' AND FORM_ID IN (SELECT a.FORM_ID FROM FM_ALIAS_GROUP as a)) )';
EXECUTE IMMEDIATE @sql_statement;
IF LENGTH(@aoi_name) = 0 THEN
SET @sql_statement = 'INSERT INTO WELL_FORMATION(UWI, FORM_ID, SOURCE, FORM_OBS_NO, GX_FORM_TOP_DEPTH, GX_FORM_TOP_TVD,GX_FORM_Y_COORDINATE, GX_FORM_X_COORDINATE) ON EXISTING UPDATE
(SELECT p.UWI as "Well ID", p.FORM_ID as "Formation",''' || @source_name || ''' as "Source", p.FORM_OBS_NO as "Observation Number",
(SELECT GX_FORM_TOP_DEPTH FROM WELL_FORMATION WHERE UWI = p.UWI and FORM_ID = p.FORM_ID and FORM_OBS_NO = p.FORM_OBS_NO and SOURCE = (SELECT SOURCE FROM SOURCE_PRIORITY_LIST_MEMBER WHERE LIST_NAME = ''' || @source_list || ''' AND ID = p.ID AND LENGTH(SOURCE) >0)) as "Top Depth",
(SELECT GX_FORM_TOP_TVD FROM WELL_FORMATION WHERE UWI = p.UWI and FORM_ID = p.FORM_ID and FORM_OBS_NO = p.FORM_OBS_NO and SOURCE = (SELECT SOURCE FROM SOURCE_PRIORITY_LIST_MEMBER WHERE LIST_NAME = ''' || @source_list || ''' AND ID = p.ID AND LENGTH(SOURCE) >0)) as "Top TVD",
(SELECT GX_FORM_Y_COORDINATE FROM WELL_FORMATION WHERE UWI = p.UWI and FORM_ID = p.FORM_ID and FORM_OBS_NO = p.FORM_OBS_NO and SOURCE =
(SELECT SOURCE FROM SOURCE_PRIORITY_LIST_MEMBER WHERE LIST_NAME = ''' || @source_list || ''' AND ID = p.ID AND LENGTH(SOURCE) >0 )),
(SELECT GX_FORM_X_COORDINATE FROM WELL_FORMATION WHERE UWI = p.UWI and FORM_ID = p.FORM_ID and FORM_OBS_NO = p.FORM_OBS_NO and SOURCE =
(SELECT SOURCE FROM SOURCE_PRIORITY_LIST_MEMBER WHERE LIST_NAME = ''' || @source_list || ''' AND ID = p.ID AND LENGTH(SOURCE) >0))
FROM
(SELECT d.UWI, d.FORM_ID, d.FORM_OBS_NO, MIN(d.ID) as "ID" FROM
(SELECT c.UWI as "UWI", c.FORM_ID as "FORM_ID" , c.SOURCE as "SOURCE", c.FORM_OBS_NO as "FORM_OBS_NO", c.GX_FORM_TOP_TVD as "TVD", a.ID as "ID", c.GX_FORM_TOP_DEPTH as "GX_FORM_TOP_DEPTH" FROM "DBA"."WELL_FORMATION" as c, SOURCE_PRIORITY_LIST_MEMBER as a
WHERE a.SOURCE = c.SOURCE AND a.LIST_NAME = ''' || @source_list || ''' and c."FORM_ID" IN (SELECT FORM_ID FROM #TEMPCOLUMN)) as d
WHERE GX_FORM_TOP_DEPTH IS NOT NULL AND UWI IN (SELECT UWI FROM #TEMPFILTER)
GROUP BY d.UWI, d.FORM_ID, d.FORM_OBS_NO) as p)';
ELSE
SET @sql_statement =  'INSERT INTO WELL_FORMATION(UWI, FORM_ID, SOURCE, FORM_OBS_NO, GX_FORM_TOP_DEPTH, GX_FORM_TOP_TVD,GX_FORM_Y_COORDINATE, GX_FORM_X_COORDINATE) ON EXISTING UPDATE
(SELECT p.UWI as "Well ID", p.FORM_ID as "Formation",''' || @source_name || ''' as "Source", p.FORM_OBS_NO as "Observation Number",
(SELECT GX_FORM_TOP_DEPTH FROM WELL_FORMATION WHERE UWI = p.UWI and FORM_ID = p.FORM_ID and FORM_OBS_NO = p.FORM_OBS_NO and SOURCE = (SELECT SOURCE FROM SOURCE_PRIORITY_LIST_MEMBER WHERE LIST_NAME = ''' || @source_list || ''' AND ID = p.ID AND LENGTH(SOURCE) >0)) as "Top Depth",
(SELECT GX_FORM_TOP_TVD FROM WELL_FORMATION WHERE UWI = p.UWI and FORM_ID = p.FORM_ID and FORM_OBS_NO = p.FORM_OBS_NO and SOURCE = (SELECT SOURCE FROM SOURCE_PRIORITY_LIST_MEMBER WHERE LIST_NAME = ''' || @source_list || ''' AND ID = p.ID AND LENGTH(SOURCE) >0)) as "Top TVD",
(SELECT GX_FORM_Y_COORDINATE FROM WELL_FORMATION WHERE UWI = p.UWI and FORM_ID = p.FORM_ID and FORM_OBS_NO = p.FORM_OBS_NO and SOURCE =
(SELECT SOURCE FROM SOURCE_PRIORITY_LIST_MEMBER WHERE LIST_NAME = ''' || @source_list || ''' AND ID = p.ID AND LENGTH(SOURCE) >0)),
(SELECT GX_FORM_X_COORDINATE  FROM WELL_FORMATION WHERE UWI = p.UWI and FORM_ID = p.FORM_ID and FORM_OBS_NO = p.FORM_OBS_NO and SOURCE =
(SELECT SOURCE FROM SOURCE_PRIORITY_LIST_MEMBER WHERE LIST_NAME = ''' || @source_list || ''' AND ID = p.ID AND LENGTH(SOURCE) >0))
FROM
(SELECT d.UWI, d.FORM_ID, d.FORM_OBS_NO, MIN(d.ID) as "ID" FROM
(SELECT c.UWI as "UWI", c.FORM_ID as "FORM_ID" , c.SOURCE as "SOURCE", c.FORM_OBS_NO as "FORM_OBS_NO", c.GX_FORM_TOP_TVD as "TVD", a.ID as "ID", c.GX_FORM_TOP_DEPTH as "GX_FORM_TOP_DEPTH" FROM "DBA"."WELL_FORMATION" as c, SOURCE_PRIORITY_LIST_MEMBER as a
WHERE a.SOURCE = c.SOURCE AND a.LIST_NAME = ''' || @source_list || ''' and c."FORM_ID" IN (SELECT FORM_ID FROM #TEMPCOLUMN)) as d
WHERE GX_FORM_TOP_DEPTH IS NOT NULL AND UWI IN (SELECT UWI FROM #TEMPFILTER) AND UWI IN (SELECT UWI FROM #TEMPAOIVIEW)
GROUP BY d.UWI, d.FORM_ID, d.FORM_OBS_NO) as p)';
END IF;
EXECUTE IMMEDIATE @sql_statement;
END